#pragma once

#include <string>

#include "mlx/backend/metal/device.h"

namespace mini_sglang_mlx {
namespace jit {

// Embedded metal sources (generated by tools/gen_jit_source.py).
extern const char* paged_prefill_attention_metal_source;
extern const char* paged_decode_attention_metal_source;

}  // namespace jit

#ifdef _METAL_

// Load a kernel library, compiling it at runtime if needed.
//
// The MPP cooperative tensor layout depends on the Metal language version
// used at compile time. Offline `xcrun metal` compilation produces a layout
// that does not match the MPP runtime on this OS/Xcode, corrupting MMA
// operand placement. Compiling at runtime via MTL::newLibrary with
// MTL::LanguageVersion4_0 (the same path MLX uses for its own kernels)
// produces the correct layout.
inline MTL::Library* get_jit_library(
    mx::metal::Device& d,
    const std::string& name,
    const char* source) {
  return d.get_library(name, [source]() { return std::string(source); });
}

#endif

}  // namespace mini_sglang_mlx
