#!/usr/bin/env python3
"""Generate a C++ file embedding the metal kernel sources for runtime JIT.

The MPP cooperative tensor layout depends on the Metal language version used
at compile time. Offline `xcrun metal` compilation produces a layout that
does not match the one the MPP runtime uses; compiling at runtime via
MTL::newLibrary with MTL::LanguageVersion4_0 (the path MLX itself uses)
produces the correct layout. This script inlines the small MLX helper
headers (the runtime compiler cannot take -I paths) and emits a C++ file
with the sources as string constants.

Usage: gen_jit_source.py <out.cpp> <min_header.h> <src1.metal> [src2.metal ...]
"""

import sys


def main():
    out_path, min_header_path, *metal_paths = sys.argv[1:]
    min_header = open(min_header_path).read()

    chunks = []
    for mp in metal_paths:
        src = open(mp).read()
        src = src.replace(
            '#include "mlx/backend/metal/kernels/utils.h"', min_header
        )
        name = mp.split("/")[-1].replace(".", "_").replace("-", "_")
        chunks.append((name, src))

    with open(out_path, "w") as f:
        f.write("// Auto-generated by gen_jit_source.py — do not edit.\n")
        f.write("#include <string>\n\n")
        f.write("namespace mini_sglang_mlx {\nnamespace jit {\n\n")
        for name, src in chunks:
            f.write(f"const char* {name}_source = R\"METAL(\n{src})METAL\";\n\n")
        f.write("}  // namespace jit\n}  // namespace mini_sglang_mlx\n")


if __name__ == "__main__":
    main()
